// This file was automatically generated by json-schema-to-typescript.
// DO NOT MODIFY IT BY HAND.

export interface InstantiateMsg {
  /**
   * Initial pause state
   */
  initial_paused: boolean;
  /**
   * Owner of this contract, who can pause and unpause
   */
  owner: string;
}

export type ExecuteMsg =
  | {
      pause: {};
    }
  | {
      unpause: {};
    }
  | {
      transfer_ownership: {
        /**
         * See [`bvs_library::ownership::transfer_ownership`] for more information on this field
         */
        new_owner: string;
      };
    };

export type QueryMsg =
  | {
      is_paused: {
        /**
         * The (contract: Addr) calling this
         */
        c: string;
        /**
         * The (method: ExecuteMsg) to check if it is paused
         */
        m: string;
      };
    }
  | {
      can_execute: {
        /**
         * The (contract: Addr) calling this
         */
        c: string;
        /**
         * The (method: ExecuteMsg) to check if it is paused
         */
        m: string;
        /**
         * The (sender: Addr) of the message
         */
        s: string;
      };
    };

export type CanExecuteResponse = number;

export type IsPausedResponse = number;
