// This file was automatically generated by json-schema-to-typescript.
// DO NOT MODIFY IT BY HAND.

export interface InstantiateMsg {
  owner: string;
  pauser: string;
}

export type ExecuteMsg =
  | {
      set_vault: {
        vault: string;
        whitelisted: boolean;
      };
    }
  | {
      transfer_ownership: {
        new_owner: string;
      };
    };

export type QueryMsg =
  | {
      is_whitelisted: {
        vault: string;
      };
    }
  | {
      is_validating: {
        operator: string;
      };
    }
  | {
      list_vaults: {
        limit?: number | null;
        start_after?: string | null;
      };
    };

/**
 * The response to the `IsValidating` query. Not exported. This is just a wrapper around `bool`, so that the schema can be generated.
 */
export type IsValidatingResponse = boolean;

/**
 * The response to the `IsWhitelisted` query. Not exported. This is just a wrapper around `bool`, so that the schema can be generated.
 */
export type IsWhitelistedResponse = boolean;

/**
 * The response to the `ListVaults` query. For pagination, the `start_after` field is the last `vault` from the previous page.
 */
export type VaultListResponse = Vault[];

export interface Vault {
  vault: Addr;
  whitelisted: boolean;
}

export type Addr = string;
