// This file was automatically generated by json-schema-to-typescript.
// DO NOT MODIFY IT BY HAND.

export interface InstantiateMsg {
  owner: string;
  pauser: string;
  registry: string;
  router: string;
}

export type ExecuteMsg =
  | {
      deploy_cw20: {
        cw20: string;
      };
    }
  | {
      deploy_bank: {
        denom: string;
      };
    }
  | {
      transfer_ownership: {
        new_owner: string;
      };
    }
  | {
      set_code_id: {
        code_id: number;
        vault_type: VaultType;
      };
    };
export type VaultType = "bank" | "cw20";

export type QueryMsg = {
  code_id: {
    vault_type: VaultType;
  };
};
export type VaultType = "bank" | "cw20";

/**
 * The response to the `CodeId` query. Not exported. This is just a wrapper around `u64`, so that the schema can be generated.
 */
export type CodeIdResponse = number;
