[package]
name = "cw-bvs-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
cw-bvs-driver = { path = "../cw-bvs-driver" }
cw-state-bank = { path = "../cw-state-bank" }
