[package]
name = "cw-bvs-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
bvs-driver = { path = "../bvs-driver" }
state-bank = { path = "../state-bank" }
