version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint:
        update-types:
          - "minor"
          - "patch"
        include:
          - "eslint"
          - "husky"
          - "lint-staged"
          - "@eslint/*"
          - "eslint-*"
          - "globals"
          - "*-eslint-*"
      prettier:
        include:
          - "prettier"
          - "prettier-plugin-*"

  - package-ecosystem: cargo
    directory: "/crates"
    schedule:
      interval: "weekly"

  - package-ecosystem: gomod
    directory: "/modules"
    schedule:
      interval: "weekly"
