version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "husky"
          - "lint-staged"
          - "eslint"
          - "globals"
          - "@eslint/*"
          - "*eslint*"
        exclude-patterns:
          - "eslint-config-next"
      prettier:
        patterns:
          - "prettier"
          - "prettier-plugin-*"
      docs:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "eslint-config-next"
          - "@tailwindcss/postcss"
          - "tailwindcss"
          - "postcss"
          - "next"
          - "nextra"
          - "nextra-*"
          - "react*"
          - "@types/react*"

      cosmjs:
        patterns:
          - "@cosmjs/*"

  - package-ecosystem: cargo
    directory: "/crates"
    schedule:
      interval: "weekly"

  - package-ecosystem: gomod
    directory: "/modules"
    schedule:
      interval: "weekly"
