name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "CosmWasm"
    labels: ["a/crates"]

  - title: "@modules/babylond"
    labels: ["a/modules/babylond"]

  - title: "@modules/cosmwasm-api"
    labels: ["a/modules/cosmwasm-api"]

  - title: "@modules/cosmwasm-schema"
    labels: ["a/modules/cosmwasm-schema"]

  - title: "@examples"
    collapse-after: 5
    labels: ["a/examples"]

  - title: "Documentation"
    collapse-after: 5
    labels: ["a/docs"]
sort-by: title
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  minor:
    labels: ["s/feat"]
  default: patch
template: |
  $CHANGES
