name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Babylon Contracts (cosmos)"
    labels: ["a/crates"]

  - title: "@modules/babylond"
    labels: ["a/modules/babylond"]

  - title: "@modules/bvs-api"
    labels: ["a/modules/bvs-api"]

  - title: "@modules/bvs-cli"
    labels: ["a/modules/bvs-cli"]

  - title: "@modules/bvs-cw"
    labels: ["a/modules/bvs-cw"]

  - title: "@examples"
    collapse-after: 5
    labels: ["a/examples"]

  - title: "Documentation"
    collapse-after: 5
    labels: ["a/docs"]
sort-by: title
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  minor:
    labels: ["s/feat"]
  default: patch
template: |
  $CHANGES
