name: "Setup"
description: "Install Rust, Go, Node.js, Corepack, PNPM"

runs:
  using: "composite"
  steps:
    # Node.js and PNPM
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
    - run: npm install -g corepack@latest
      shell: bash
    - run: corepack enable pnpm
      shell: bash

    # Rust and Cache
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    # TODO: go
