name: "Setup"
description: "Install Rust, Go, Node.js, Corepack, PNPM"

runs:
  using: "composite"
  steps:
    # Rust
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "crates -> crates/target"

    # Go
    - uses: actions/setup-go@v5
      with:
        go-version-file: "modules/go.mod"
        cache-dependency-path: "modules/go.sum"

    # Node.js, PNPM, Turbo
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
    - uses: pnpm/action-setup@v4
    - run: |
        echo "NEXT_TELEMETRY_DISABLED=1" >> $GITHUB_ENV
        echo "TURBO_TELEMETRY_DISABLED=1" >> $GITHUB_ENV
        pnpm install -g turbo
        pnpm install

        # We're using Turbo for non-npm scripts as well. 
        # To suppress npm warnings, this simple script mkdir `node_modules` for all workspaces. 
        workspace_paths=$(pnpm m ls --depth=-1 --json | jq -r '.[].path')
        for path in $workspace_paths; do
          if [ ! -d "$path/node_modules" ]; then
            mkdir "$path/node_modules"
          fi
        done
      shell: bash

    # Docker
    - run: docker buildx create --use --bootstrap --driver=docker-container
      shell: bash
