[package]
name = "bvs-base"
description = "Messages and types for SatLayer CosmWasm smart contracts"
version = "2.0.0"
edition = "2021"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
