[package]
name = "bvs-registry"
version = "2.0.0"
edition = "2021"

exclude = [
    "contract.wasm",
    "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["library", "dep:strum"]
testing = ["library", "dep:cw-multi-test"]
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
strum = { version = "0.27", features = ["derive"], optional = true }
cw-multi-test = { workspace = true, optional = true }
