[package]
name = "bvs-testing"
description = "Utilities for testing BVS contracts"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }

[dependencies]
base64 = { workspace = true }
cosmwasm-std = { workspace = true }
cw-multi-test = { workspace = true }
bech32 = { workspace = true }
ripemd = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
secp256k1 = { workspace = true }
cosmwasm-crypto = { workspace = true }

bvs-delegation-manager = { workspace = true }
bvs-directory = { workspace = true }
bvs-registry = { workspace = true }
bvs-rewards-coordinator = { workspace = true }
bvs-slash-manager = { workspace = true }
bvs-strategy-base = { workspace = true }
bvs-strategy-manager = { workspace = true }
