[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.24"
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[lint]
ignore = ["test/**/*"]

[rpc_endpoints]
mainnet = "https://mainnet.gateway.tenderly.co"
sepolia = "https://sepolia.gateway.tenderly.co"
holesky = "https://holesky.gateway.tenderly.co"

[etherscan]
mainnet = { chain = 1, key = "${ETHERSCAN_API_KEY}" }
sepolia = { chain = 11155111, key = "${ETHERSCAN_API_KEY}" }
holesky = { chain = 17000, key = "${ETHERSCAN_API_KEY}" }
