[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.24"
evm_version = "cancun"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
slaynet = "${TENDERLY_RPC_URL}"

[etherscan]
slaynet = { chain = 83766589, key = "${TENDERLY_ACCESS_KEY}", url = "${TENDERLY_RPC_URL}/verify/etherscan" }
