[workspace]
members = [
    # production contracts
    "bvs-delegation-manager",
    "bvs-directory",
    "bvs-driver",
    "bvs-rewards-coordinator",
    "bvs-slash-manager",
    "bvs-state-bank",
    "bvs-strategy-base",
    "bvs-strategy-base-tvl-limits",
    "bvs-strategy-factory",
    "bvs-strategy-manager",
    "bvs-test",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["SatLayer"]
edition = "2021"
license = "MIT"
repository = "https://github.com/satlayer/satlayer-bvs.git"
homepage = "https://satlayer.xyz/"
documentation = "https://github.com/satlayer/satlayer-bvs.git"
keywords = ["SatLayer", "Restaking", "BTC", "cosmos", "cosmwasm"]

[workspace.dependencies]
cosmwasm-schema = "2.0.0"
cosmwasm-std = "2.0.0"
cw-storage-plus = "2.0.0"
cosmwasm-storage = "1.5.2"
schemars = "0.8.8"
cw2 = "2.0.0"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
cw-multi-test = "=2.0.0"
sha2 = { version = "0.10.8", default-features = false }
hex = "0.4"
cosmwasm-crypto = "2.2.1"
secp256k1 = "0.29.0"
cw20 = "2.0.0"
bech32 = "0.8.0"
ripemd = "0.1.0"
serde_json = "1.0.0"
base64 = "0.22.1"
cw-utils = "2.0.0"

# contracts
bvs-delegation-manager = { path = "./bvs-delegation-manager" }
bvs-directory = { path = "./bvs-directory" }
bvs-driver = { path = "./bvs-driver" }
bvs-rewards-coordinator = { path = "./bvs-rewards-coordinator" }
bvs-slash-manager = { path = "./bvs-slash-manager" }
bvs-state-bank = { path = "./bvs-state-bank" }
bvs-strategy-base = { path = "./bvs-strategy-base" }
bvs-strategy-base-tvl-limits = { path = "./bvs-strategy-base-tvl-limits" }
bvs-strategy-factory = { path = "./bvs-strategy-factory" }
bvs-strategy-manager = { path = "./bvs-strategy-manager" }

# common cosmwasm crates
bvs-base = { path = "./common/bvs/base" }
bvs-testing = { path = "./common/bvs/testing" }
